service: dead-lambda

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

functions:
  good:
    handler: good.test
    events:
     - http:
         path: good
         method: get
  bad:
    handler: bad.test
    events:
     - http:
         path: bad
         method: get
  ugly:
    handler: ugly.test
    events:
     - http:
         path: ugly
         method: get
